### ISSUE TITLE
Kafka input not auto-commiting

### ISSUE THREAD

**Issue by WaizungTaam** [Jeffail/benthos#736] opened 2021-04-15 08:11 UTC
Just upgraded benthos from v3.42.1 to v3.44.0，and when I use kafka as the input, the messages are not commited at all. Here is the config file:
```yaml
input:
  kafka:
    addresses:
      - 127.0.0.1:9092
    topics:
      - benthos_test

pipeline: []

output:
  type: stdout

```
When I restart benthos, all the messages will be delivered again.

I have noticed that v3.43.0 increased the offset commit API of kafka input, and have turned off the `AutoCommit.Enable`. Wonder if there a way to turn auto-commit on?

**Comment by Jeffail** [comment] 2021-04-15 08:23
Hey @WaizungTaam, which version of Kafka are you running? And do you get any interesting logs from either Benthos or Kafka?

**Comment by WaizungTaam** [comment] 2021-04-15 08:39
kafka_2.13-2.7.0, and no, just some normal logs.

By the way, the config I posted is invalid, should be:
```yaml
pipeline:
  processors: []
```

**Comment by Jeffail** [comment] 2021-04-15 08:45
Okay I can reproduce this with some new integration tests and it's a regression, disabling auto commit in the sarama config doesn't impact when consuming explicit partitions, but we still need it for partition balancing. I'll add a patch release for v3.44 since there's some changes in v3.45 that aren't ready for release quite yet.

**Comment by Jeffail** [comment] 2021-04-15 08:45
Fixed in: https://github.com/Jeffail/benthos/commit/ea7449426816025cd03d6a0c5953bfaefc650ffe

**Comment by Jeffail** [comment] 2021-04-15 09:18
Patch release out: https://github.com/Jeffail/benthos/releases/tag/v3.44.1

Thanks for raising this @WaizungTaam, turns out this was a pretty huge gap in the integration tests, there's some coverage for it now.

**Closed by Jeffail** 2021-04-15 09:18 UTC
Labels: bug, inputs
