### ISSUE TITLE
Problem consuming from redpanda when using materialized sinks using the `reuseTopic` option. (`kafka: insufficient data to decode packet, more bytes expected`)

### ISSUE THREAD

**Issue by chjdev** [Jeffail/benthos#953] opened 2021-11-19 09:31 UTC
Moving to a new issue from: https://github.com/Jeffail/benthos/issues/711#issuecomment-972643114

we have a topic where the data in (redpanda) kafka looks completely normal and i can consume it fine via cli, however when i try consume from it using benthos i get the same error, however nothing is produced to the output:

```
{"@timestamp":"2021-11-18T08:58:55+01:00","@service":"benthos","component":"incoming","level":"ERROR","message":"Kafka group message recv error: kafka: error while consuming xxx/0: kafka: insufficient data to decode packet, more bytes expected"}
```

Here's the config I used to test it, which works fine for other topics:

```yaml
http:
  address: 0.0.0.0:4195
  read_timeout: 5s
  root_path: /benthos
  debug_endpoints: false

input:
  label: incoming
  kafka:
    addresses:
      - "some_broker:31572"
    tls:
      enabled: true
      root_cas_file: /path/to/redpanda/ca.crt
      client_certs:
        - cert_file: /path/to/redpanda/cluster.crt
          key_file: /path/to/redpanda/cluster.key
    sasl:
      mechanism: "SCRAM-SHA-256"
      user: "user"
      password: "password"
    topics: [ "some_topic" ]
    consumer_group: some_consumer_group
    client_id: some_client_id
    checkpoint_limit: 1

buffer:
  type: none
  none: {}

output:
  label: "output"
  stdout:
    codec: lines
```

The specific topic in question was produced via a meterialize sink (with the reuse topic option enabled) which according to @senior7515 should work identically and is tested through integration tests on redpanda's side. (see original issue)

Any idea what might be going on here?

We're running
Benthos version: 3.58.0
Redpanda: v21.9.6

---

We've prepared a docker-compose that can reproduce the bug here: https://github.com/chjdev/benthos-bug-repro .

What we're observing is if benthos starts immediately, it consumes the messages from the (materialize sink) topic right away, then hits the above error.
However if we delay the start, then it will hit the error first and not consume any messages.
This only seems to happen if we use the topic reuse option of materialize which presumably uses control messages. It might be a red herring but I've also seen that the offsets in the reuse case start at `1` and in the non reuse case at `0`.

![image](https://user-images.githubusercontent.com/973941/142622775-0b9ac1a4-cd97-4ace-9da2-1ca050f00931.png)

**Comment by Jeffail** [comment] 2021-11-19 13:18
Thanks @chjdev that's perfect. I think this is all the information we'll need to get started.

**Comment by Jeffail** [comment] 2021-12-07 19:39
Okay so I've done a bit of digging around and I can see that the problem on the client side is when decoding control messages from the topic, we seem to be receiving messages that have a key value of `\x00\x00\x00\x01`, but an empty body and that's causing the client to fail and stop consuming (as it doesn't know how to proceed). Relevant code here: https://github.com/Shopify/sarama/blob/main/consumer.go#L699.

This is reproducible with Redpanda by enabling idempotency and transactions, and then running any form of transaction based producer. In your example that's what materialize is doing but I've also reproduced it using [`kcl`](https://github.com/twmb/kcl), and I've [attached the configs](https://github.com/Jeffail/benthos/files/7671130/redpanda-transactions.tar.gz) used for that.

I can run the same components using regular kafka/zookeeper and we do not have this issue so my belief is that this is an unexpected message coming from redpanda specifically. It may be that this is a loosely defined area of the kafka protocols and so clients treat the message differently (it looks as though some other clients are simply ignoring the control message), but it's also possible that this is an actual bug within redpanda.

@senior7515 is there any chance someone from redpanda can take a quick look? If we can confirm it's a valid control message then I can look into providing an upstream bug report/fix.

In the meantime we could look into patching a fork of the sarama client to ignore the messages, but that's not something I'd be comfortable running long term.

**Comment by BenPope** [comment] 2021-12-07 20:25
There have been a tonne of fixes, including Tx ones, and filtering of control messages since v21.9.6, it's definitely worth trying v21.11.1.

**Comment by Jeffail** [comment] 2021-12-07 20:38
@BenPope I was able to reproduce it with the tag `v21.11.1-beta2`

**Comment by BenPope** [comment] 2021-12-07 20:53
Ahh. Thanks for testing. We'll take a look.

**Comment by twmb** [comment] 2021-12-07 22:29
AFAICT this is because Sarama is strict on the semantics of what a control record should look like (specifically, only transactional control records). Redpanda is injecting control records that Sarama does not understand. I'm not sure why the control record is empty -- perhaps @rystsov can clarify.

**Comment by rystsov** [comment] 2021-12-07 22:38
Sarama client [makes assumptions](https://github.com/Shopify/sarama/blob/99c86c94517e2fd32b457461c59988ce02fc82c2/control_record.go#L50) about the value of the control markers while the docs specify that it should be opaque to the clients.

> The schema for the value of a control record is dependent on the type. The value is opaque to clients.

https://kafka.apache.org/documentation/#controlbatch

**Comment by Jeffail** [comment] 2021-12-07 23:01
Awesome, thanks @BenPope @twmb @rystsov for the details, I'll follow up with the sarama maintainers.

**Comment by rystsov** [comment] 2021-12-08 16:28
@Jeffail it's all you! your initial investigation, minimal reproducible example and the link to the Sarama source helped me a lot, thank you!

**Comment by BenPope** [comment] 2021-12-09 22:45
This should be fixed: https://github.com/vectorizedio/redpanda/releases/tag/v21.11.2

**Comment by Jeffail** [comment] 2021-12-09 23:06
@BenPope that's awesome, thank you!

**Comment by BenPope** [comment] 2021-12-09 23:18
I'm just the messenger, thanks go to you and @rystsov

**Comment by Jeffail** [comment] 2021-12-13 19:47
@chjdev I've also added a new `kafka_franz` input and output https://github.com/Jeffail/benthos/commit/46af1ff1d17d73e580e878257469aefb639d5d49, these use a different kafka client implementation (https://github.com/twmb/franz-go), so for any future issues there's an alternative we can try out as a potential short term solution. Closing this issue for now but if you have any further problems please either reopen it or create a new one.

**Closed by Jeffail** 2021-12-13 19:47 UTC
Labels: inputs, needs investigation
