### ISSUE TITLE
1s limit on reject output

### ISSUE THREAD

**Issue by iluminae** [Jeffail/benthos#704] opened 2021-03-18 20:28 UTC
Hi there,
I have a config that I am using that is fairly high throughput using pubsub:
```yaml
input:
  gcp_pubsub:
    project: myproj
    subscription: mysubscription
    max_outstanding_messages: 40000
    batching:
      count: 500
      period: "5s"
processors:
- type: somethingThatMightFail
output:
  switch:
    retry_until_success: false
    cases:
    - check: errored()
      output:
        reject: |
          project=${! meta("projectId") } error=${! error() }
    - output:
        drop: {}
```
and sometimes my processor will error out (eg if the database it is talking to is down). When it does error, the error does correctly get applied to the parts and it will fall down into the reject output - but when this happens, I get _exactly_ 1 message/s throughput. I would _expect_ it to nack pubsub and continue along as fast as it can. Where is the 1s coming from here? Note it is still 1s even if I change/remove the batching from the input. I looked at the code for the reject output and its literally just return `errors.New()` so I assume it has something to do with errors propagating to inputs? I have reproduced this 1s limit in your WASM lab with the reject output.

Is there a better way I can be propagating these nacks while still performing the rest of my work as fast as I can?

Thanks!

**Comment by Jeffail** [comment] 2021-03-18 20:48
Hey @iluminae, this is actually being caused at the input level https://github.com/Jeffail/benthos/blob/master/lib/input/async_reader.go#L168, basically it's a back pressure mechanism that prevents a busy loop when messages that will never succeed are being attempted with an input that doesn't propagate acknowledgements upstream. In your case that mechanism isn't required since we're pushing those failed messages upstream.

It should be possible to disable that mechanism selectively for inputs that support upstream acks and then we'll unlock the throughput for rejected messages.

**Comment by iluminae** [comment] 2021-03-18 21:07
Sweet, that would feel better for pubsub for sure. Probably will cost me more if im spinning on errors but im ok with that.

**Comment by Jeffail** [comment] 2021-03-21 10:54
Needs a bit of manual testing to go along with the integration test suites but I believe this is fixed with: https://github.com/Jeffail/benthos/commit/e1f2faef07877676563df41c9781efd1dcd761bc

It turns out I was wrong and that there's a general purpose rate limit for all output types. I've removed that and added a rate limiter at the input level that specifically only applies to inputs that do not push nacks upstream, this also has the advantage of rate limits applying to the individual failing message and not to the general output.

**Comment by Jeffail** [comment] 2021-03-21 17:36
There was a small regression but it looks good in local tests now.

**Closed by Jeffail** 2021-03-21 17:36 UTC
Labels: annoying, inputs
