### ISSUE TITLE
Recommendations for preserving ordering for Kafka producer

### ISSUE THREAD

**Issue by zlozano** [Jeffail/benthos#550] opened 2020-11-11 20:31 UTC
The provided Kafka output covers a lot of my current use cases. Something I'm trying to wrap my head around is how ordering may be affected in a degraded state (e.g. intermittent network latency, intermittent broker issues). When operating on a batch of messages, it's possible that one message within the batch could fail. The sarama client has a [mechanism](https://github.com/Shopify/sarama/blob/master/async_producer.go#L489-L492) for preserving ordering within a partition for sending messages. In order for this to be effective, there are a few [settings](https://blog.softwaremill.com/does-kafka-really-guarantee-the-order-of-messages-3ca849fd19d2) that need to be tweaked.

Since the benthos retry policy effectively replaces the sarama strategy, I think there is a chance of messages getting delivered out of order in certain scenarios. I'm thinking of some ways to do this without having to maintain my own Kafka producer, though that is still a valid way of going about it. In order to decorate the Kafka producer with custom metrics + tracing I have a custom plugin that calls the `writer.NewKafka` function and wraps the writer with my own writer implementations. With this in mind, a couple of preliminary ideas I had:

Have a new function which allows for a base sarama config:

1. New factory func which allows injection of base sarama config
```
type Kafka struct {
	log   log.Modular
	mgr   types.Manager
	stats metrics.Type

        ...
        confProvider func() *sarama.Config
}

// NewKafka creates a new Kafka writer type.
func NewKafka(conf KafkaConfig, mgr types.Manager, log log.Modular, stats metrics.Type) (*Kafka, error) {

        ...

	k := Kafka{
		log:   log,
		mgr:   mgr,
		stats: stats,

		confProvider: sarama.NewConfig,

                ...
	}

	...

	return &k, nil
}

func NewKafkaWithBaseConfig(conf KafkaConfig, mgr types.Manager, log log.Modular, stats metrics.Type, cp func() *sarama.Config) (*Kafka,error) {
        k, err := NewKafka(conf, mgr, log, stats)
        if err != nil {
                return nil, err
        }
        k.confProvider = cp
        return k, nil
}

func (k *Kafka) Connect() error {
        ...
        config := k.configProvider() // base sarama producer config is set here
        ...
}

```

2. Export the producer
```
/* some custom plugin */
type kafka struct {
	*writer.Kafka
         bc writer.KafkaConfig
         sc *sarama.Config
}

func newKafka(conf writer.KafkaConfig, mgr types.Manager, log log.Modular, stats metrics.Type, sc *sarma.Config) (*kafka, error) {
	k, err := writer.NewKafka(conf, mgr, log, stats)
	if err != nil {
		return nil, err
	}
	return &kafka{Kafka: k, bc: conf, sc: sc}, nil
}

func (k *kafka) Connect() error {
        k.Kafka.Lock()
        defer k.Kafka.Lock() // would likely need to export this some how to safely access/modify producer

        // construct producer

        k.Producer = p
}
        
```

These are pretty half baked though.

Happy to hear your thoughts.

**Comment by Jeffail** [comment] 2020-11-11 21:41
Hey @zlozano, that's a really interesting one and a bit of a doozy. I think it should be possible to have a benthos configuration that ensures ordering, but it might require disabling individual message retries in batching. It's possible to enforce only one batch in flight at a given time as that's the default, and you can block an alternative batch being tried after a failed batch gets requeued by wrapping a `kafka` output with a `retry`. However, the problem is that if a message batch partially succeeds, where only a few messages fail, then only the failed messages get tried again which would break ordering here.

I'll need to do a review of the current state of affairs but I don't think it'll be needed for you to have a custom output in order to get the guarantee.

**Comment by zlozano** [comment] 2020-11-11 21:47
Yeah that makes sense.

> However, the problem is that if a message batch partially succeeds, where only a few messages fail, then only the failed messages get tried again which would break ordering here.

This is the use case I'm primarily focussed on. The sarama client uses a strategy to account for this (for messages destined for the same partition). But since we are sitting one layer above this protocol, it's tough to control this using the current configuration options.

Thanks for taking a look at this!

**Comment by Jeffail** [comment] 2020-11-22 14:49
Hey @zlozano, I've added a new field `retry_as_batch` to the kafka output: https://github.com/Jeffail/benthos/commit/1543f10deac5ab845c8a97674a2448cd03ae05a2, setting this field plus a few other retry fields would ensure that messages are never delivered out of order, with the main trade off being the increased possibility of duplicate messages and the need for manual intervention for send errors that are related to incorrect config parameters (or any non-recoverable errors).

I think this is probably as close as we can get when sending within a transaction model without doing the partition allocation manually, otherwise we're trading off strict delivery guarantees in favour of reduced chance of duplicates. I'll paste the newly added docs section here so you can review it:

> When strict ordering is required for messages written to topic partitions it is important to ensure that both the field `max_in_flight` is set to `1` and that the field `retry_as_batch` is set to `true`.
>
>  You must also ensure that failed batches are never rerouted back to the same output. This can be done by setting the field `max_retries` to `0` and `backoff.max_elapsed_time` to empty, which will apply back pressure indefinitely until the batch is sent successfully.
>
>  However, this also means that manual intervention will eventually be required in cases where the batch cannot be sent due to configuration problems such as an incorrect `max_msg_bytes` estimate. A less strict but automated alternative would be to route failed batches to a dead letter queue using a [`try` broker](https://www.benthos.dev/docs/components/outputs/try), but this would allow subsequent batches to be delivered in the meantime whilst those failed batches are dealt with.

**Comment by zlozano** [comment] 2020-11-26 05:00
Awesome! I believe this will do. Thanks!

**Comment by Jeffail** [comment] 2020-12-15 19:25
Forgot to update this, the new field was released in: https://github.com/Jeffail/benthos/releases/tag/v3.35.0

**Closed by Jeffail** 2020-12-15 19:25 UTC
Labels: outputs, question
