### ISSUE TITLE
aws_kinesis input GetRecords backoff timer gets clobbered

### ISSUE THREAD

**Issue by Gerald-Lim-Bose** [Jeffail/benthos#1104] opened 2022-02-04 22:24 UTC
In the aws_kinesis input, when no records are returned by a get records operation, I believe the intent is for there to be a backoff period before the next get records call is made: https://github.com/Jeffail/benthos/blob/bda960d4522912f24edbf32926961ace1978fde5/lib/input/aws_kinesis.go#L413 

(The same goes for when an error other than timeout occurs during the get records call).

However, it looks like the line below later on reassigns the `nextPullChan` channel reference to the `unblockedChan` channel, so the backoff period never really takes effect and the get records operation in the next loop runs immediately: https://github.com/Jeffail/benthos/blob/bda960d4522912f24edbf32926961ace1978fde5/lib/input/aws_kinesis.go#L457

In sparsely populated Kinesis streams (when GetRecords frequently return no records), this causes the AWS API rate limit of 5 GetRecords calls per second to get hit. Interestingly, the only evidence of this is in the AWS CloudWatch metrics for the stream (GetRecords.Success average will be less than 100% and ReadProvisionThroughputExceeded average percentage will be greater than 0%). On the client side, the AWS go SDK is not returning the ProvisionedThroughputExceededException error for some reason, so I'm not surprised this wasn't detected.

**Comment by Jeffail** [comment] 2022-02-05 10:50
Hey @Gerald-Lim-Bose, thanks for raising this, looks like you're right. I'll have a fix to try out shortly, just running some integration tests.

**Comment by Jeffail** [comment] 2022-02-05 11:04
Fix: https://github.com/Jeffail/benthos/commit/7a5496e31d827d34bb4d861be30d3dcf3e8801fb. Unfortunately my integration test suite doesn't have checks for rate limits so I can't reproduce the issue locally. I'm planning a release early next week, if you have a chance to try this out in the meantime let me know.

**Comment by Jeffail** [comment] 2022-02-07 17:27
Going to close this for now but if the issue shows up again please reopen. Releasing either this evening or tomorrow.

**Closed by Jeffail** 2022-02-07 17:27 UTC
Labels: bug, inputs
