### ISSUE TITLE
Enhancement: Nats Streaming disconnect when connection is stale

### ISSUE THREAD

**Issue by thinktainer** [Jeffail/benthos#142] opened 2019-01-10 13:50 UTC
Currently when the connection to the nats streaming server is interrupted in any way, the client will not be notified of this. The nats streaming client library offers a mechanism that allows the client to react to loss of connection (see: https://github.com/nats-io/go-nats-streaming#connection-status).

This proposal is to suggest to make the input report the disconnected status, passing control about what to do with this case (probably hooking into here somehow: https://github.com/Jeffail/benthos/blob/master/lib/input/reader/nats_stream.go#L192).

I haven't looked with much detail at the output side of this, but would assume that similar modifications would be useful there too.

**Comment by Jeffail** [comment] 2019-01-10 14:35
Cool, thanks for pointing this out @thinktainer, I'll take a look.

**Comment by Jeffail** [comment] 2019-01-10 16:27
@thinktainer, I think I have a fix for this: https://github.com/Jeffail/benthos/commit/324af296ef27b0db2503f936d8b67859d9b2b564, is reproducing this issue as simple as disconnecting the server for a period of time?

I'm assuming the output is okay since it's a synchronous call being made, so if the connection has been lost I would hope an error is returned, but I'll check it as well just to be sure.

**Comment by Jeffail** [comment] 2019-01-10 16:57
Okay I've managed to reproduce and that fix wasn't quite enough, also the output wasn't able to recover either. I've got a fix that seems to work well for both: https://github.com/Jeffail/benthos/commit/5b882012821dddf0f5474c11f9f7e0a920b7ed08

**Comment by thinktainer** [comment] 2019-01-11 10:23
Amazing, thank you for the fast turn around, i'll play around with that today!

**Comment by Jeffail** [comment] 2019-01-14 09:55
Closing this, please reopen if you find any issues.

**Closed by Jeffail** 2019-01-14 09:55 UTC
Labels: enhancement, inputs, outputs

**Comment by thinktainer** [comment] 2019-01-15 10:48
all good, thank you!
